# Generated by Django 6.0.5 on 2026-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudySpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("location", models.CharField(max_length=300)),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("amenities", models.JSONField(default=list)),
                ("rating", models.FloatField(default=4.0)),
                ("image_url", models.URLField(blank=True, default="")),
                ("is_open_24h", models.BooleanField(default=False)),
                (
                    "hours",
                    models.CharField(blank=True, default="9am - 10pm", max_length=100),
                ),
                (
                    "noise_level",
                    models.CharField(
                        choices=[
                            ("silent", "Silent"),
                            ("quiet", "Quiet"),
                            ("moderate", "Moderate"),
                        ],
                        default="quiet",
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "study_spots",
            },
        ),
    ]
