# Generated by Django 6.0.5 on 2026-05-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studysession",
            name="recurrence_day",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
