# Generated by Django 6.0.5 on 2026-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_message", "New Message"),
                            ("session_reminder", "Session Reminder"),
                            ("group_invite", "Group Invite"),
                            ("group_join", "Group Join"),
                            ("session_created", "Session Created"),
                            ("streak_milestone", "Streak Milestone"),
                            ("ai_response", "AI Response"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("is_read", models.BooleanField(default=False)),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
