# Generated by Django 6.0.5 on 2026-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "group_memberships",
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "course_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exam_prep", "Exam Prep"),
                            ("assignment_help", "Assignment Help"),
                            ("coding_session", "Coding Session"),
                            ("quiet_studying", "Quiet Studying"),
                            ("project_collab", "Project Collaboration"),
                            ("general", "General Study"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("max_members", models.PositiveSmallIntegerField(default=20)),
                (
                    "invite_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("avatar_color", models.CharField(default="#6366f1", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "study_groups",
                "ordering": ["-created_at"],
            },
        ),
    ]
