# Generated by Django 6.0.5 on 2026-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStudyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("minutes_studied", models.IntegerField(default=0)),
                ("sessions_completed", models.IntegerField(default=0)),
                ("subjects", models.JSONField(default=list)),
            ],
            options={
                "db_table": "daily_study_logs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StudyStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_study_date", models.DateField(blank=True, null=True)),
                ("total_study_days", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "study_streaks",
            },
        ),
    ]
